server:
    port: 3107

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        id:
          new_generator_mappings: false
    cache:
      type: caffeine
      caffeine:
        spec:
          expireAfterWrite: 600s
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: localhost:9200
  cassandra:
    schema-action: CREATE_IF_NOT_EXISTS
    username: ndtrong
    password: ndtrong
    local-datacenter: datacenter1
    request:
      timeout: 10s
    port: '9042'
    connection:
      init-query-timeout: 10s
      connect-timeout: 10s
    contact-points: 127.0.0.1
    keyspace-name: ks_book
  main:
    allow-bean-definition-overriding: true